version: '3'

services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    environment:
      TARGET_SERVER_URL: http://host.docker.internal:3020
      ENCRYPTION_SERVICE_URL: http://encryption-service-url/encrypt
